name: Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[Bug]: "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: "## Thanks for reporting a bug! Please fill out the details below."
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, or runtime details
      placeholder: "Windows 11, Chrome 115"
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What did you do to trigger the bug?
      placeholder: "1. Go to...\n2. Click on...\n3. See error..."
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "It should have..."
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: "Instead, it..."
