blank_issues_enabled: false
contact_links:
  - name: 💬 Get Help or Ask a Question
    url: https://github.com/joeskeen/github-readme-tabs/blob/main/.github/SUPPORT.md
    about: For general questions or support, check here first.
