name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: "## Got an idea? We’d love to hear it!"
  - type: input
    id: motivation
    attributes:
      label: What problem does this solve?
      placeholder: "I want to be able to..."
  - type: textarea
    id: proposal
    attributes:
      label: Describe the feature
      placeholder: "Add a button that..."
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: "I tried using..."
